"""add document processing metadata

Revision ID: 1f393585a113
Revises: f10bdf1b8cb6
Create Date: 2026-09-05 12:06:03.643060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f393585a113'
down_revision: Union[str, Sequence[str], None] = 'f10bdf1b8cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=False))
    op.add_column('documents', sa.Column('char_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'char_count')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
